site:
  title: PPWCode .NET Docs
  start_page: ppwcode-net::index.adoc
content:
  # disable edit url for now
  # don't want inline editing pages
  edit_url: ~
  sources:
    - url: .
      branches: HEAD
    - url: https://github.com/peopleware/net-ppwcode-vernacular-contracts
      branches:
        - I/next
      start_path: docs
    - url: https://github.com/peopleware/net-ppwcode-vernacular-exceptions
      branches:
        - IV/next
      start_path: docs
    - url: https://github.com/peopleware/net-ppwcode-vernacular-exceptions
      branches:
        - V/next
      start_path: docs
    - url: https://github.com/peopleware/net-ppwcode-vernacular-semantics
      branches:
        - IV/next
      start_path: docs
    - url: https://github.com/peopleware/net-ppwcode-vernacular-semantics
      branches:
        - V/next
      start_path: docs
    - url: https://github.com/peopleware/net-ppwcode-vernacular-persistence
      branches:
        - IV/next
      start_path: docs
    - url: https://github.com/peopleware/net-ppwcode-vernacular-persistence
      branches:
        - V/next
      start_path: docs
    - url: https://github.com/peopleware/net-ppwcode-vernacular-nhibernate
      branches:
        - III/next
      start_path: docs
    - url: https://github.com/peopleware/net-ppwcode-util-validation
      branches:
        - III/next
      start_path: docs
    - url: https://github.com/peopleware/net-ppwcode-util-validation
      branches:
        - IV/next
      start_path: docs
    - url: https://github.com/peopleware/net-ppwcode-util-authorization
      branches:
        - I/next
      start_path: docs
    - url: https://github.com/peopleware/net-ppwcode-util-collection
      branches:
        - I/next
      start_path: docs
    - url: https://github.com/peopleware/net-ppwcode-util-di
      branches:
        - I/next
      start_path: docs
    - url: https://github.com/peopleware/net-ppwcode-util-time
      branches:
        - I/next
      start_path: docs
    - url: https://github.com/peopleware/net-ppwcode-api-core
      branches:
        - next
      start_path: docs
    - url: https://github.com/peopleware/net-ppwcode-server-core
      branches:
        - next
      start_path: docs
    - url: https://github.com/peopleware/net-ppwcode-server-core-hangfire
      branches:
        - next
      start_path: docs
    - url: https://github.com/peopleware/net-ppwcode-server-core-nservicebus
      branches:
        - next
      start_path: docs
    - url: https://github.com/peopleware/net-ppwcode-host-core
      branches:
        - next
      start_path: docs
    - url: https://github.com/peopleware/net-ppwcode-host-core-hangfire
      branches:
        - next
      start_path: docs
    - url: https://github.com/peopleware/net-ppwcode-host-core-webapi
      branches:
        - next
      start_path: docs
ui:
  bundle:
    # for local tests: use a file reference
    # url: '../docs-ui/build/ui-bundle.zip'
    url: https://github.com/peopleware/net-ppwcode-docs-ui/releases/download/0.0.8/ui-bundle.zip
  supplemental_files: ./ui
antora:
  extensions:
    - require: '@antora/lunr-extension'
      index_by_heading: true
