site:
  title: PPWCode .NET Docs (under construction)
  start_page: ppwcode-net::index.adoc
content:
  sources:
    - url: .
      branches: HEAD
    - url: https://github.com/peopleware/net-ppwcode-vernacular-contracts
      branches:
        - I/next
      start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./ui
