site:
  title: PPWCode .NET Docs
  start_page: ppwcode-net::index.adoc
content:
  sources:
    - url: .
      branches: HEAD
    - url: https://github.com/peopleware/net-ppwcode-vernacular-contracts
      branches:
        - I/next
      start_path: docs
    - url: https://github.com/peopleware/net-ppwcode-vernacular-exceptions
      branches:
        - IV/next
      start_path: docs
ui:
  bundle:
    # for local tests: use a file reference
    # url: '../docs-ui/build/ui-bundle.zip'
    url: https://github.com/peopleware/net-ppwcode-docs-ui/releases/download/0.0.8/ui-bundle.zip
  supplemental_files: ./ui
antora:
  extensions:
    - require: '@antora/lunr-extension'
      index_by_heading: true
